spring:
  application:
    name: Auth-Service

  # Database Configuration
  datasource:
    # We reference the variables defined in .env
    url: ${NEON_URI}
    username: ${NEON_USER}
    password: ${NEON_PASS}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Optimization for Neon/Cloud DBs (Optional but recommended)
        jdbc:
          batch_size: 50



server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The URL of your Eureka Server
    register-with-eureka: true
    fetch-registry: true

