server:
  port: 8082

spring:
  application:
    name: USER-SERVICE # This is the name the Gateway will use to route requests [cite: 10, 144]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/User-Service
    username: postgres
    password: Sujal9730

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The URL of your Eureka Server
    register-with-eureka: true
    fetch-registry: true
