#spring.application.name=Job-Service
#server:
  #port: 8084

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # OLD: org.springframework.kafka.support.serializer.JsonSerializer
      # NEW:
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
  application:
    name : Job-Service
  datasource:
    # We reference the variables defined in .env
    url: ${NEON_URI}
    username: ${NEON_USER}
    password: ${NEON_PASS}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Optimization for Neon/Cloud DBs (Optional but recommended)
        jdbc:
          batch_size: 50

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The URL of your Eureka Server
    register-with-eureka: true
    fetch-registry: true
