#server:
  #port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group   # Unique ID for this service
      auto-offset-reset: earliest    # If no history found, start from the beginning

      # 1. MATCHING DESERIALIZERS (Mirror of your Producer)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.example.Notification_Service.DTO.JobEvent

            use:
              type:
                headers: false
        # 2. CRITICAL SECURITY SETTING
        # This allows the consumer to accept objects from the Job Service package.
        # "*" means "Trust all packages". Without this, you will get a Security Error.
        #spring.json.trusted.packages: "*"
  application:
    name : NOTIFICATION-SERVICE
  datasource:
    # We reference the variables defined in .env
    url: ${NEON_URI}
    username: ${NEON_USER}
    password: ${NEON_PASS}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Optimization for Neon/Cloud DBs (Optional but recommended)
        jdbc:
          batch_size: 50

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The URL of your Eureka Server
    register-with-eureka: true
    fetch-registry: true

